apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    git: https://github.com/prometheus-community/helm-charts
    ref: master
    path: charts/kube-prometheus-stack
  values:
    serviceName: prometheus