apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-repository
  namespace: monitoring
spec:
  interval: 1m
  url: https://github.com/prometheus-community/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m
  releaseName: prometheus
  chart:
    spec:
      chart: charts/kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-repository